const validPaths = [
  "/snapArt/dashboard",
  "/snapArt/allTasks",
  "/snapArt/myTasks",
  "/snapArt/completedTasks",
  "/snapArt/task_participants",
  "/snapArt/verifiedTasks",
  "/snapArt/taskCategories",
  "/snapArt/allAdverts",
  "/snapArt/products",
  "/snapArt/subscriptions",
  "/snapArt/allCompetitions",
  "/snapArt/completeCompetitions",
  "/snapArt/upcomingCompetitions",
  "/snapArt/ongoingCompetitions",
  "/snapArt/competitors",
  "/snapArt/widthdrawTrans",
  "/snapArt/depositTrans",
  "/snapArt/rewardTrans",
  "/snapArt/paymentTrans",
  "/snapArt/transactionsHistory",
  "/snapArt/exchanges",
  "/snapArt/assets",
  "/snapArt/myAccount",
  "/snapArt/holding",
  "/snapArt/youtube",
  "/snapArt/twitter",
  "/snapArt/tiktok",
  "/snapArt/facebook",
  "/snapArt/instagram",
  "/snapArt/telegram",
  "/snapArt/snapchat",
  "/snapArt/users",
];

export default validPaths;
